<#
.SYNOPSIS
    Moves the zyeute project from antigravity to ZyeuteV5 and verifies the move.
    
.DESCRIPTION
    This script performs a safe copy (robocopy /MIR) from C:\Users\north\antigravity\zyeute 
    to C:\Users\north\ZyeuteV5\zyeute.
    It verifies file counts and sizes, then installs dependencies.

.NOTES
    Generated by Antigravity Agent.
#>

$SourcePath = "C:\Users\north\antigravity\zyeute"
$DestPath = "C:\Users\north\ZyeuteV5\zyeute"

Write-Host "=== Zyeute Migration Helper ===" -ForegroundColor Cyan
Write-Host "Source:      $SourcePath"
Write-Host "Destination: $DestPath"
Write-Host "==============================`n"

# 1. Validation
if (-not (Test-Path $SourcePath)) {
    Write-Error "CRITICAL: Source path '$SourcePath' does not exist."
    Write-Host "Please verify where 'zyeute' currently resides."
    exit 1
}

# 2. Execution
Write-Host "Starting safe copy (Robocopy Mirror)..."
# /MIR :: Mirror dictionary hierarchy.
# /MT:8 :: Multi-threaded copy (8 threads) for speed.
# /R:3 /W:3 :: Retry 3 times, wait 3 seconds on failure.
robocopy $SourcePath $DestPath /MIR /MT:8 /R:3 /W:3

# Robocopy exit codes: 0-7 are success/partial success (files copied)
if ($LASTEXITCODE -gt 7) {
    Write-Error "Robocopy failed with exit code $LASTEXITCODE"
    exit 1
}

# 3. Verification
Write-Host "`nVerifying integrity..."
$srcStats = Get-ChildItem $SourcePath -Recurse -File | Measure-Object -Property Length -Sum
$dstStats = Get-ChildItem $DestPath -Recurse -File | Measure-Object -Property Length -Sum

$srcCount = $srcStats.Count
$srcSize = $srcStats.Sum
$dstCount = $dstStats.Count
$dstSize = $dstStats.Sum

Write-Host "Source:      $srcCount files, $([math]::Round($srcSize/1MB, 2)) MB"
Write-Host "Destination: $dstCount files, $([math]::Round($dstSize/1MB, 2)) MB"

if ($srcCount -eq $dstCount -and $srcSize -eq $dstSize) {
    Write-Host "SUCCESS: File count and size match exactly." -ForegroundColor Green
} else {
    Write-Warning "MISMATCH: The source and destination do not match exactly."
    Write-Warning "Check the output above for errors."
    # We allow safe continuation if user wants, but prompt? 
    # For now, we pause.
    $confirmation = Read-Host "Do you want to continue with dependency installation? (y/n)"
    if ($confirmation -ne 'y') { exit }
}

# 4. Setup
Write-Host "`nSetting up environment in $DestPath..."
Set-Location $DestPath

if (Test-Path "package.json") {
    Write-Host "Node.js project detected. Installing dependencies..."
    # Prefer npm ci if lockfile exists, else install
    if (Test-Path "package-lock.json") {
        npm ci
    } else {
        npm install
    }
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Dependencies installed." -ForegroundColor Green
        
        # Optional: Run tests if script exists
        $pkg = Get-Content "package.json" | ConvertFrom-Json
        if ($pkg.scripts.test) {
            Write-Host "Running tests..."
            npm test
        }
    } else {
        Write-Error "npm install failed."
    }
} elseif (Test-Path "requirements.txt") {
    Write-Host "Python project detected. (Setup logic can be added here)"
}

Write-Host "`nMigration complete. You can now delete the source if desired." -ForegroundColor Cyan
