/**
 * Video Engine
 * Real FAL/Kling/Wan integration for video generation
 */

import { fal } from "@fal-ai/client";

// Helper to get FAL key
function getFalKey() {
  return process.env.FAL_API_KEY || process.env.FAL_KEY;
}

// Initial config if key exists
const initialKey = getFalKey();
if (initialKey) {
  fal.config({ credentials: initialKey });
}

export interface VideoGenerationParams {
  prompt: string;
  imageUrl?: string; // For image-to-video
  duration?: number;
  modelHint?: "kling" | "wan" | "hunyuan_video" | "ltx2" | "ltx-2" | "pollo";
}

export interface VideoGenerationResult {
  url: string;
  cost: number;
  model: string;
  duration: number;
}

export async function generateVideo(
  params: VideoGenerationParams,
): Promise<VideoGenerationResult> {
  const { prompt, imageUrl, duration = 5, modelHint = "kling" } = params;

  console.log(
    `[Video Engine] Generating video (${modelHint}):`,
    prompt.substring(0, 50),
  );

  const currentKey = getFalKey();
  if (!currentKey) {
    console.warn(
      "[Video Engine] FAL API key not configured, returning placeholder. Please set FAL_KEY in .env.",
    );
    return {
      url: "https://placehold.co/1920x1080/1a1a1a/gold?text=FAL_KEY+Missing+In+Env",
      cost: 0,
      model: "placeholder",
      duration: 0,
    };
  }

  // Ensure fal client is configured with the latest key
  fal.config({ credentials: currentKey });

  try {
    // -------------------------------------------------------------
    // WAN VIDEO MODEL (NEW)
    // -------------------------------------------------------------
    if (modelHint === "wan") {
      const model = imageUrl
        ? "fal-ai/wan/v2.2-a14b/image-to-video"
        : "fal-ai/wan/v2.2-a14b/text-to-video";

      console.log(`[Video Engine] Running Wan Video generation (${model})...`);

      const input: any = {
        prompt,
        // The Wan model might have different parameter names or requirements
        // but fal-ai usually standardizes on prompt/image_url
        aspect_ratio: "9:16",
      };

      if (imageUrl) {
        input.image_url = imageUrl;
      }

      const result = await fal.subscribe(model, {
        input,
        logs: true,
      });

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Wan model");
      }

      return {
        url: video.url,
        cost: 0.6,
        model: `wan-v2.2-${imageUrl ? "i2v" : "t2v"}`,
        duration: 5,
      };
    }

    // -------------------------------------------------------------
    // LTX-2 MODEL (NEW)
    // -------------------------------------------------------------
    if (modelHint === "ltx2" || modelHint === "ltx-2") {
      const model = imageUrl
        ? "fal-ai/ltx-2-19b/image-to-video"
        : "fal-ai/ltx-2-19b/text-to-video";

      console.log(
        `[Video Engine] Running LTX-2 Video generation (${model})...`,
      );

      const input: any = {
        prompt,
        aspect_ratio: "9:16",
      };

      if (imageUrl) {
        input.image_url = imageUrl;
      }

      const result = await fal.subscribe(model, {
        input,
        logs: true,
      });

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by LTX-2 model");
      }

      return {
        url: video.url,
        cost: 0.8, // Guessing cost/credit weight
        model: `ltx2-19b-${imageUrl ? "i2v" : "t2v"}`,
        duration: 5,
      };
    }

    // -------------------------------------------------------------
    // POLLO AI MODEL (NEW)
    // -------------------------------------------------------------
    if (modelHint === "pollo") {
      console.log(`[Video Engine] Running Pollo AI generation...`);
      const { PolloService } = await import("../../services/tikapi-service.js");

      const task = await PolloService.generateVideo({
        prompt,
        aspect_ratio: "9:16",
        quality: "hd",
        duration: duration === 10 ? 10 : 5,
      });

      // Pollo is asynchronous, we poll or wait for the first check
      // For this engine's synchronous contract, we'll wait briefly for completion
      let attempts = 0;
      while (attempts < 30) {
        // 30 * 5s = 150s max wait
        await new Promise((resolve) => setTimeout(resolve, 5000));
        const status = await PolloService.getTaskStatus(task.taskId);

        if (status.status === "completed" && status.videoUrl) {
          return {
            url: status.videoUrl,
            cost: 1.2, // Pollo HD cost
            model: "pollo-hd-v1",
            duration: duration,
          };
        }

        if (status.status === "failed") {
          throw new Error(`Pollo AI generation failed: ${status.error}`);
        }

        attempts++;
        console.log(
          `[Video Engine] Pollo AI task ${task.taskId} still processing (attempt ${attempts})...`,
        );
      }

      throw new Error("Pollo AI generation timed out");
    }

    // -------------------------------------------------------------
    // KLING MODEL (EXISTING)
    // -------------------------------------------------------------
    // Use image-to-video if imageUrl provided, otherwise text-to-video
    if (imageUrl) {
      const result = await fal.subscribe(
        "fal-ai/kling-video/v2/master/image-to-video",
        {
          input: {
            image_url: imageUrl,
            prompt,
            duration: String(duration) as "5" | "10",
          },
          logs: true,
        },
      );

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Kling model");
      }

      return {
        url: video.url,
        cost: 0.5, // Approximate cost per Kling video
        model: "kling-i2v",
        duration,
      };
    } else {
      // Text-to-video using Kling V2
      console.log("[Video Engine] Running Kling text-to-video generation...");
      const result = await fal.subscribe(
        "fal-ai/kling-video/v2/master/text-to-video",
        {
          input: {
            prompt,
            duration: String(duration) as "5" | "10",
            aspect_ratio: "9:16", // Optimized for mobile/TikTok
          },
          logs: true,
        },
      );

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Kling model");
      }

      return {
        url: video.url,
        cost: 0.5,
        model: "kling-t2v",
        duration,
      };
    }
  } catch (error: any) {
    console.error(
      `[Video Engine] ${modelHint} generation failed:`,
      error.message,
    );
    throw error;
  }
}
