/**
 * Video Engine
 * Real FAL/Kling/Wan integration for video generation
 */

import { fal } from "@fal-ai/client";

// Resolve FAL key from various possible env names
const FAL_API_KEY = process.env.FAL_API_KEY || process.env.FAL_KEY;

// Configure FAL if not already done
if (FAL_API_KEY) {
  fal.config({ credentials: FAL_API_KEY });
}

export interface VideoGenerationParams {
  prompt: string;
  imageUrl?: string; // For image-to-video
  duration?: number;
  modelHint?: "kling" | "wan" | "hunyuan_video";
}

export interface VideoGenerationResult {
  url: string;
  cost: number;
  model: string;
  duration: number;
}

export async function generateVideo(
  params: VideoGenerationParams,
): Promise<VideoGenerationResult> {
  const { prompt, imageUrl, duration = 5, modelHint = "kling" } = params;

  console.log(
    `[Video Engine] Generating video (${modelHint}):`,
    prompt.substring(0, 50),
  );

  if (!FAL_API_KEY) {
    console.warn(
      "[Video Engine] FAL API key not configured, returning placeholder. Please set FAL_KEY in .env.",
    );
    return {
      url: "https://placehold.co/1920x1080/1a1a1a/gold?text=FAL_KEY+Missing+In+Env",
      cost: 0,
      model: "placeholder",
      duration: 0,
    };
  }

  try {
    // -------------------------------------------------------------
    // WAN VIDEO MODEL (NEW)
    // -------------------------------------------------------------
    if (modelHint === "wan") {
      const model = imageUrl
        ? "fal-ai/wan-video/v2.1/image-to-video"
        : "fal-ai/wan-video/v2.1/text-to-video";

      console.log(`[Video Engine] Running Wan Video generation (${model})...`);

      const input: any = {
        prompt,
        aspect_ratio: "9:16",
      };

      if (imageUrl) {
        input.image_url = imageUrl;
      }

      const result = await fal.subscribe(model, {
        input,
        logs: true,
      });

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Wan model");
      }

      return {
        url: video.url,
        cost: 0.6, // Wan 2.1 is slightly more expensive usually
        model: `wan-v2.1-${imageUrl ? "i2v" : "t2v"}`,
        duration: 5,
      };
    }

    // -------------------------------------------------------------
    // KLING MODEL (EXISTING)
    // -------------------------------------------------------------
    // Use image-to-video if imageUrl provided, otherwise text-to-video
    if (imageUrl) {
      const result = await fal.subscribe(
        "fal-ai/kling-video/v2/master/image-to-video",
        {
          input: {
            image_url: imageUrl,
            prompt,
            duration: String(duration) as "5" | "10",
          },
          logs: true,
        },
      );

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Kling model");
      }

      return {
        url: video.url,
        cost: 0.5, // Approximate cost per Kling video
        model: "kling-i2v",
        duration,
      };
    } else {
      // Text-to-video using Kling V2
      console.log("[Video Engine] Running Kling text-to-video generation...");
      const result = await fal.subscribe(
        "fal-ai/kling-video/v2/master/text-to-video",
        {
          input: {
            prompt,
            duration: String(duration) as "5" | "10",
            aspect_ratio: "9:16", // Optimized for mobile/TikTok
          },
          logs: true,
        },
      );

      const video = (result.data as any)?.video;
      if (!video?.url) {
        throw new Error("No video generated by Kling model");
      }

      return {
        url: video.url,
        cost: 0.5,
        model: "kling-t2v",
        duration,
      };
    }
  } catch (error: any) {
    console.error(
      `[Video Engine] ${modelHint} generation failed:`,
      error.message,
    );
    throw error;
  }
}
