import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

const isValidUrl = (url: string | undefined) => {
  try {
    return url && new URL(url).protocol.startsWith("http");
  } catch (e) {
    return false;
  }
};

// No-op lock: bypass Navigator LockManager to prevent 10s timeout (auth-js#1594)
const noOpLock = async <R>(
  _name: string,
  _acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> => fn();

// Create real Supabase client
export const supabase = createClient(supabaseUrl || "", supabaseAnonKey || "", {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    lock: noOpLock,
  },
});

/** getSession with timeout - prevents feed/API from hanging if auth is slow. */
export async function getSessionWithTimeout(ms = 3000): Promise<{
  data: { session: { access_token: string } | null };
}> {
  try {
    const result = await Promise.race([
      supabase.auth.getSession(),
      new Promise<{ data: { session: null } }>((resolve) =>
        setTimeout(() => resolve({ data: { session: null } }), ms),
      ),
    ]);
    return result;
  } catch {
    return { data: { session: null } };
  }
}

// Check Supabase credentials
const credentialsMissing = !isValidUrl(supabaseUrl) || !supabaseAnonKey;

if (credentialsMissing) {
  if (process.env.NODE_ENV === "production") {
    console.error(
      "❌ CRITICAL: Supabase credentials missing in production! The app will likely fail to load.",
    );
  } else {
    console.warn("⚠️ [SECURITY] Supabase credentials missing or invalid.");
  }
}

// Helper function to get dynamic redirect URL based on current domain
function getRedirectUrl(): string {
  // Always use current origin to support all domains:
  // - https://zyeute.com
  // - https://zyeute.ca
  // - https://zyeute-v3.vercel.app
  // - http://localhost:5173 (dev)
  const origin = window.location.origin;
  return `${origin}/auth/callback`;
}

// Helper functions
export async function getCurrentUser() {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  return user;
}

export async function signIn(email: string, password: string) {
  return await supabase.auth.signInWithPassword({ email, password });
}

export async function signUp(
  email: string,
  password: string,
  username: string,
) {
  const redirectUrl = getRedirectUrl();

  return await supabase.auth.signUp({
    email,
    password,
    options: {
      data: { username },
      emailRedirectTo: redirectUrl,
    },
  });
}

export async function signOut() {
  return await supabase.auth.signOut();
}

export async function signInWithGoogle() {
  const redirectUrl = getRedirectUrl();

  console.log("🔍 Google OAuth redirect URL:", redirectUrl);

  return await supabase.auth.signInWithOAuth({
    provider: "google",
    options: {
      redirectTo: redirectUrl,
    },
  });
}

export async function uploadFile(bucket: string, path: string, file: File) {
  const { data, error } = await supabase.storage
    .from(bucket)
    .upload(path, file);
  if (error) return { url: null, error };
  const { data: urlData } = supabase.storage.from(bucket).getPublicUrl(path);
  return { url: urlData.publicUrl, error: null };
}

export async function deleteFile(bucket: string, path: string) {
  const { error } = await supabase.storage.from(bucket).remove([path]);
  return { error };
}

export function subscribeToTable(
  table: string,
  callback: (payload: any) => void,
) {
  const channel = supabase
    .channel(`public:${table}`)
    .on("postgres_changes", { event: "*", schema: "public", table }, callback)
    .subscribe();

  return () => {
    supabase.removeChannel(channel);
  };
}

// WebAuthn Biometric Authentication
export async function signInWithBiometrics() {
  try {
    // Check if WebAuthn is supported
    if (!window.PublicKeyCredential) {
      throw new Error("WebAuthn not supported in this browser");
    }

    const { data, error } = await supabase.auth.signInWithWebAuthn({
      options: {
        authenticatorSelection: {
          authenticatorAttachment: "platform", // Built-in biometrics (Touch ID, Face ID, Windows Hello)
          userVerification: "required",
          residentKey: "preferred",
        },
        timeout: 60000, // 60 seconds
        challenge: new Uint8Array(32), // Will be generated by Supabase
      },
    });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error("Biometric authentication failed:", error);
    return { data: null, error };
  }
}

export async function registerBiometrics(email: string) {
  try {
    if (!window.PublicKeyCredential) {
      throw new Error("WebAuthn not supported in this browser");
    }

    const { data, error } = await supabase.auth.signUpWithWebAuthn({
      email,
      options: {
        authenticatorSelection: {
          authenticatorAttachment: "platform",
          userVerification: "required",
          residentKey: "required",
        },
        attestation: "direct",
        timeout: 60000,
      },
    });

    if (error) throw error;
    return { data, error: null };
  } catch (error) {
    console.error("Biometric registration failed:", error);
    return { data: null, error };
  }
}

// Check if biometric authentication is available
export async function isBiometricAvailable(): Promise<boolean> {
  try {
    if (!window.PublicKeyCredential) return false;

    // Check if platform authenticator is available
    const available =
      await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
    return available;
  } catch {
    return false;
  }
}
